spring:
  application:
    name: kotlin-test
    
  datasource:
    url: jdbc:h2:file:/tmp/employee
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    
  jackson:
    deserialization:
      FAIL_ON_NULL_FOR_PRIMITIVES: true
